'use strict';
// 跨平台自启：Windows 计划任务 / macOS launchd LaunchAgent / Linux systemd user 单元。
// 机制映射与决策记录见 docs/adr/0005，「自启任务」词条见 CONTEXT.md。
// 三平台语义对齐：
//   register    登录自动拉起 + 崩溃自愈 + 日志追加写数据目录 logs/service.log
//   stop guard  `lanbook stop` 先调它防复活（win 写停止标记 / mac bootout / linux
//               systemctl stop），服务本次停下、下次登录自启恢复
//   remove      彻底卸载（注销任务 / 删 plist / 删 unit + 附属文件）
// bin 只做参数解析与平台化输出；系统调用经 run 注入（默认 spawnSync），
// platform / homeDir / xdgConfigHome / uid 均可注入——单测在任意平台上覆盖三平台分支。
const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawnSync } = require('node:child_process');
const { initDataDir, resolveDataDir } = require('./data-dir');
const { resolveListen } = require('./settings');

// 自启任务名：Windows 计划任务名 / macOS launchd Label 与 plist 文件名 /
// Linux systemd 单元基名（LANBOOK_AUTOSTART_TASK 仅供测试隔离覆盖）
function autostartTaskName() {
  return (process.env.LANBOOK_AUTOSTART_TASK || '').trim() || 'lanbook-autostart';
}

// 默认系统命令执行器（测试注入 fake run 替换）
function defaultRun(cmd, args, opts = {}) {
  return spawnSync(cmd, args, { encoding: 'utf8', windowsHide: true, ...opts });
}

function platformOf(opts) {
  return (opts && opts.platform) || process.platform;
}
function homeDirOf(opts) {
  return (opts && opts.homeDir) || os.homedir();
}
function xdgConfigHomeOf(opts) {
  return (opts && opts.xdgConfigHome !== undefined) ? opts.xdgConfigHome : process.env.XDG_CONFIG_HOME;
}
function uidOf(opts) {
  if (opts && opts.uid !== undefined) return opts.uid;
  return typeof process.getuid === 'function' ? process.getuid() : 0;
}

// ---------- 通用路径 ----------

// 服务日志：三平台统一追加写数据目录 logs/service.log
function serviceLogPath(dataDir) {
  return path.join(dataDir, 'logs', 'service.log');
}

// ---------- macOS launchd ----------

function launchdPlistPath(label, homeDir = os.homedir()) {
  return path.join(homeDir, 'Library', 'LaunchAgents', `${label}.plist`);
}

function xmlEscape(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function xmlUnescape(s) {
  return String(s).replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
}

// LaunchAgent plist（RunAtLoad：注册即启动、登录加载时拉起；KeepAlive：崩溃立即保活，
// 等价 Windows 守护循环 / systemd Restart——launchd 会话存活期间服务不会长期死掉，
// 因此 Windows 需要的「解锁触发」在 macOS 上天然覆盖）
function generateLaunchdPlist({ label, nodeBin, serverJs, logPath }) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    '\t<key>Label</key>',
    `\t<string>${xmlEscape(label)}</string>`,
    '\t<key>ProgramArguments</key>',
    '\t<array>',
    `\t\t<string>${xmlEscape(nodeBin)}</string>`,
    `\t\t<string>${xmlEscape(serverJs)}</string>`,
    '\t</array>',
    '\t<key>RunAtLoad</key>',
    '\t<true/>',
    '\t<key>KeepAlive</key>',
    '\t<true/>',
    '\t<key>StandardOutPath</key>',
    `\t<string>${xmlEscape(logPath)}</string>`,
    '\t<key>StandardErrorPath</key>',
    `\t<string>${xmlEscape(logPath)}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

// ---------- Linux systemd user ----------

function systemdUserDir(opts = {}) {
  const xdg = xdgConfigHomeOf(opts);
  const base = (typeof xdg === 'string' && xdg.trim()) || path.join(homeDirOf(opts), '.config');
  return path.join(base, 'systemd', 'user');
}
function systemdUnitPath(unitBase, opts = {}) {
  return path.join(systemdUserDir(opts), `${unitBase}.service`);
}

// systemd user 单元：Restart=on-failure + RestartSec=3 对齐 Windows 守护循环的
// 「崩溃 3 秒后重启」；日志 StandardOutput/Error=append: 追加写（需 systemd >= 240）。
// WantedBy=default.target：用户登录（user manager 启动）时拉起。
function generateSystemdUnit({ nodeBin, serverJs, logPath }) {
  return [
    '[Unit]',
    'Description=lanbook service (generated by `lanbook autostart`)',
    '',
    '[Service]',
    // 路径一律双引号包裹：LANBOOK_HOME 可指向含空格的目录
    `ExecStart="${nodeBin}" "${serverJs}"`,
    'Restart=on-failure',
    'RestartSec=3',
    `StandardOutput=append:${logPath}`,
    `StandardError=append:${logPath}`,
    '',
    '[Install]',
    'WantedBy=default.target',
    '',
  ].join('\n');
}

// ---------- Windows 包装脚本路径（注册产物 + describe 共用） ----------

function windowsWrapperPaths(dataDir) {
  return {
    vbsPath: path.join(dataDir, 'autostart.vbs'),
    cmdPath: path.join(dataDir, 'autostart-task.cmd'),
    logPath: serviceLogPath(dataDir),
    stopFlag: path.join(dataDir, '.service-stopped'),
    busyFlag: path.join(dataDir, '.service-busy'),
  };
}

// ---------- 自启状态描述（一份真相：CLI status 提示与 pi 扩展 /lanbook status 共用） ----------
//
// 返回 { registered, via, target, launcher }：
//   registered  是否已注册（以各平台的注册产物文件是否存在为准）
//   target      自启脚本 / plist / unit 里写的 server.js 绝对路径（解析失败为 null）
//   launcher    已注册时拉起服务的命令（win: 守护脚本；mac: kickstart；linux: systemctl start）

function describeAutostart(opts = {}) {
  const dataDir = opts.dataDir || resolveDataDir();
  const platform = platformOf(opts);
  const name = autostartTaskName();

  if (platform === 'win32') {
    const { cmdPath } = windowsWrapperPaths(dataDir);
    if (!fs.existsSync(cmdPath)) return { registered: false, via: '计划任务', target: null, launcher: null };
    const m = fs.readFileSync(cmdPath, 'utf-8').match(/"([^"]*server\.js)"/);
    return {
      registered: true, via: '计划任务', target: m ? m[1] : null,
      launcher: { cmd: 'cmd', args: ['/c', 'start', '', cmdPath] },
    };
  }
  if (platform === 'darwin') {
    const plistPath = launchdPlistPath(name, homeDirOf(opts));
    if (!fs.existsSync(plistPath)) return { registered: false, via: 'launchd', target: null, launcher: null };
    // ProgramArguments 的第二个 <string> 是 server.js（第一个是 node 可执行文件）
    const m = fs.readFileSync(plistPath, 'utf-8').match(/<string>([^<]*server\.js)<\/string>/);
    return {
      registered: true, via: 'launchd', target: m ? xmlUnescape(m[1]) : null,
      launcher: { cmd: 'launchctl', args: ['kickstart', `gui/${uidOf(opts)}`, name] },
    };
  }
  if (platform === 'linux') {
    const unitPath = systemdUnitPath(name, opts);
    if (!fs.existsSync(unitPath)) return { registered: false, via: 'systemd', target: null, launcher: null };
    const m = fs.readFileSync(unitPath, 'utf-8').match(/ExecStart=.*?"([^"]*server\.js)"/);
    return {
      registered: true, via: 'systemd', target: m ? m[1] : null,
      launcher: { cmd: 'systemctl', args: ['--user', 'start', `${name}.service`] },
    };
  }
  return { registered: false, via: null, target: null, launcher: null };
}

// ---------- 注册 ----------

function registerAutostart(opts) {
  const { dataDir, serverJs } = opts;
  if (!dataDir || !serverJs) throw new Error('registerAutostart 需要 dataDir 与 serverJs');
  const run = opts.run || defaultRun;
  const platform = platformOf(opts);
  const name = autostartTaskName();
  const nodeBin = process.execPath;

  if (platform === 'win32') return registerWindows({ dataDir, serverJs, taskName: name, run });
  if (platform === 'darwin') return registerMacOS({ dataDir, serverJs, label: name, nodeBin, run, opts });
  if (platform === 'linux') return registerLinux({ dataDir, serverJs, unitBase: name, nodeBin, run, opts });
  throw new Error(`不支持的平台: ${platform}（支持 Windows / macOS / Linux）`);
}

// Windows：计划任务 → wscript(autostart.vbs 隐藏窗口) → autostart-task.cmd(守护循环)
// → node server.js。任务以当前用户身份注册、仅本人登录时触发，无需管理员。
function registerWindows({ dataDir, serverJs, taskName, run }) {
  const notes = [];
  initDataDir(dataDir, path.join(__dirname, '..'));
  const { vbsPath, cmdPath, logPath, stopFlag, busyFlag } = windowsWrapperPaths(dataDir);
  fs.mkdirSync(path.dirname(logPath), { recursive: true });

  // 端口探测用的端口：忽略进程环境里的 PORT（自启场景没有它），
  // 与服务运行时的取端口方式保持一致（数据目录 settings.json）
  const { port: probePort } = resolveListen(dataDir, {});

  // 生成的包装脚本内容保持纯 ASCII（cmd / wscript 对非 ASCII 编码敏感）
  fs.writeFileSync(vbsPath, [
    `' lanbook autostart wrapper (generated by \`lanbook autostart\`; re-register overwrites)`,
    `' Hidden-window launch; port/host come from settings.json in the data directory`,
    `CreateObject("WScript.Shell").Run """${cmdPath}""", 0, False`,
    '',
  ].join('\n'), 'utf-8');
  // 守护循环：服务进程退出后，若没有停止标记则 3 秒后自动重启（崩溃自愈）。
  // `lanbook stop` 会写停止标记 → 循环检测到标记即退出，服务不会复活。
  //
  // 拉起前先探端口：解锁触发会让计划任务再起一个守护，而上一轮服务往往还活着。
  // 无条件拉起只会撞 EADDRINUSE 退出，守护再 3 秒后重试——同一行错误无上限刷屏
  // （实测本机 121,324 行 / 11MB，占日志 99.87%）。端口已在监听时转 30 秒周期的
  // 待命：服务真挂了、端口一释放即接上。
  //
  // 待命提示写进 busyFlag 文件而不是 service.log：cmd 的 `>>` 把日志句柄传给 node
  // 子进程并继承，服务运行期间该文件被独占——而待命恰好只在服务在跑时触发，
  // 写 service.log 会报“另一个程序正在使用此文件”而静默丢失。busyFlag 不被服务持有，
  // 且“文件存在”本身就抑制重复提示，内容即诊断信息。
  //
  // 启动前 `set "PORT="`：扩展经 launcher 拉起守护时，cmd 继承宿主环境；宿主
  // （pi / pi-web）自己的 PORT（如 30141）一旦渗透，server.js 会绑到别人占用
  // 已久的端口上，EADDRINUSE 退出 → 守护 3 秒一轮无限重启刷日志。自启服务的
  // 端口只认 settings.json，PORT 一律清空（与 resolveListen(dataDir, {}) 一致）。
  fs.writeFileSync(cmdPath, [
    `@echo off`,
    `rem lanbook service launcher (generated by \`lanbook autostart\`; crash-restart guardian)`,
    `rem loop: restart unless a stop marker exists (written by \`lanbook stop\`)`,
    `:loop`,
    `if exist "${stopFlag}" exit /b 0`,
    `netstat -ano -p tcp | findstr /r /c:":${probePort} .*LISTENING" >nul 2>&1`,
    `if not errorlevel 1 (`,
    `  if not exist "${busyFlag}" echo [standby] port ${probePort} is already listening; guardian paused > "${busyFlag}"`,
    `  timeout /t 30 /nobreak >nul`,
    `  goto loop`,
    `)`,
    `if exist "${busyFlag}" del "${busyFlag}" >nul 2>&1`,
    `rem clear foreign PORT (e.g. the host's own) so the service binds the`,
    `rem settings.json port only`,
    `set "PORT="`,
    `"${process.execPath}" "${serverJs}" >> "${logPath}" 2>&1`,
    `if exist "${stopFlag}" exit /b 0`,
    `timeout /t 3 /nobreak >nul`,
    `goto loop`,
    '',
  ].join('\n'), 'utf-8');

  // 注册前清掉旧的停止 / 待命标记（重新注册 = 重新启用守护）
  for (const f of [stopFlag, busyFlag]) {
    try { fs.rmSync(f); } catch {}
  }

  // PowerShell 注册（PS 单引号串内 ' 翻倍转义；Argument 值带双引号防路径空格）
  const psArg = `"${vbsPath}"`.replace(/'/g, "''");
  const psScript = [
    `$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument '${psArg}'`,
    `$triggers = @()`,
    `$triggers += New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME`,
    `$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -ExecutionTimeLimit ([TimeSpan]::Zero)`,
    `Register-ScheduledTask -TaskName '${taskName.replace(/'/g, "''")}' -Action $action -Trigger $triggers -Settings $settings -Force | Out-Null`,
  ].join('; ');
  const reg = run('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', psScript]);
  if (reg.status !== 0) {
    throw new Error(`注册计划任务失败（exit ${reg.status}）\n${reg.stderr || reg.stdout}`);
  }
  const query = run('schtasks', ['/Query', '/TN', taskName]);
  if (query.status !== 0) throw new Error(`注册后查询不到任务 ${taskName}，注册可能未生效`);

  // 追加「工作站解锁」触发器：SessionStateChangeTrigger 无 PowerShell cmdlet 包装，
  // 用 schtasks /XML 导出-合并-导回方式（先取现有 XML，插入解锁触发，再重注册）。
  // 这样锁屏/睡眠唤醒解锁后服务也会被拉起，弥补「仅登录触发」在长期不重启机器上的空窗。
  try {
    const xmlOut = run('schtasks', ['/Query', '/TN', taskName, '/XML']).stdout || '';
    if (xmlOut.includes('<SessionStateChangeTrigger>')) {
      notes.push('解锁触发器已存在，跳过');
    } else {
      const merged = xmlOut.replace(
        /<\/Triggers>/,
        `    <SessionStateChangeTrigger>\n      <StateChange>SessionUnlock</StateChange>\n      <UserId>${process.env.USERNAME || ''}</UserId>\n    </SessionStateChangeTrigger>\n  </Triggers>`,
      );
      const xmlPath = path.join(dataDir, 'autostart-task.xml');
      fs.writeFileSync(xmlPath, merged, 'utf8');
      const reReg = run('schtasks', ['/Create', '/TN', taskName, '/XML', xmlPath, '/F']);
      try { fs.rmSync(xmlPath); } catch {}
      if (reReg.status === 0) {
        notes.push('已追加工作站解锁触发器（锁屏/唤醒后自动拉起服务）');
      } else {
        notes.push(`追加解锁触发器失败（不影响登录触发）：${(reReg.stderr || '').trim()}`);
      }
    }
  } catch (err) {
    notes.push(`追加解锁触发器异常（不影响登录触发）：${err.message}`);
  }

  return { kind: 'windows', taskName, vbsPath, cmdPath, logPath, notes };
}

// macOS：launchd LaunchAgent。RunAtLoad 使 bootstrap 即启动；KeepAlive 崩溃保活。
function registerMacOS({ dataDir, serverJs, label, nodeBin, run, opts }) {
  initDataDir(dataDir, path.join(__dirname, '..'));
  const logPath = serviceLogPath(dataDir);
  fs.mkdirSync(path.dirname(logPath), { recursive: true });
  const plistPath = launchdPlistPath(label, homeDirOf(opts));
  fs.mkdirSync(path.dirname(plistPath), { recursive: true });
  fs.writeFileSync(plistPath, generateLaunchdPlist({ label, nodeBin, serverJs, logPath }), 'utf-8');

  const guiTarget = `gui/${uidOf(opts)}`;
  // 先卸旧实例再加载：重复注册 = 覆盖（bootout 失败仅说明当前未加载，忽略）
  run('launchctl', ['bootout', `${guiTarget}/${label}`]);
  const bs = run('launchctl', ['bootstrap', guiTarget, plistPath]);
  if (bs.status !== 0) {
    throw new Error(`launchctl bootstrap 失败（exit ${bs.status}）\n${(bs.stderr || bs.stdout || '').trim()}\n`
      + `（纯 SSH 无图形登录会话时 launchd 用户域不可用，请在桌面会话中注册）`);
  }
  return { kind: 'launchd', label, plistPath, logPath, uid: uidOf(opts), notes: [] };
}

// Linux：systemd user 单元。daemon-reload 后 enable --now（注册即启动 + 登录自启）。
function registerLinux({ dataDir, serverJs, unitBase, nodeBin, run, opts }) {
  initDataDir(dataDir, path.join(__dirname, '..'));
  const logPath = serviceLogPath(dataDir);
  fs.mkdirSync(path.dirname(logPath), { recursive: true });
  const unitPath = systemdUnitPath(unitBase, opts);
  fs.mkdirSync(path.dirname(unitPath), { recursive: true });
  fs.writeFileSync(unitPath, generateSystemdUnit({ nodeBin, serverJs, logPath }), 'utf-8');
  const unitName = `${unitBase}.service`;

  const reload = run('systemctl', ['--user', 'daemon-reload']);
  if (reload.status !== 0) {
    throw new Error(`systemctl --user daemon-reload 失败（exit ${reload.status}）\n${(reload.stderr || '').trim()}\n`
      + `（容器 / 无 systemd 的环境不支持 systemd user 单元）`);
  }
  const enable = run('systemctl', ['--user', 'enable', '--now', unitName]);
  if (enable.status !== 0) {
    throw new Error(`systemctl --user enable --now ${unitName} 失败（exit ${enable.status}）\n${(enable.stderr || '').trim()}`);
  }
  return { kind: 'systemd', unitName, unitPath, logPath, notes: [] };
}

// ---------- 卸载 ----------

function removeAutostart(opts = {}) {
  const run = opts.run || defaultRun;
  const platform = platformOf(opts);
  const name = autostartTaskName();

  if (platform === 'win32') {
    const res = run('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command',
      `Unregister-ScheduledTask -TaskName '${name.replace(/'/g, "''")}' -Confirm:$false`]);
    const removed = res.status === 0;
    // 包装脚本是注册时生成的附属物，一并清理（不存在则忽略）
    const dataDir = opts.dataDir || resolveDataDir();
    for (const f of ['autostart.vbs', 'autostart-task.cmd', 'autostart-task.xml', '.service-stopped', '.service-busy']) {
      try { fs.rmSync(path.join(dataDir, f)); } catch {}
    }
    return { kind: 'windows', taskName: name, removed };
  }
  if (platform === 'darwin') {
    const plistPath = launchdPlistPath(name, homeDirOf(opts));
    if (!fs.existsSync(plistPath)) return { kind: 'launchd', label: name, removed: false };
    run('launchctl', ['bootout', `gui/${uidOf(opts)}/${name}`]); // 未加载时失败无害
    try { fs.rmSync(plistPath); } catch {}
    return { kind: 'launchd', label: name, removed: true };
  }
  if (platform === 'linux') {
    const unitPath = systemdUnitPath(name, opts);
    if (!fs.existsSync(unitPath)) return { kind: 'systemd', unitName: `${name}.service`, removed: false };
    run('systemctl', ['--user', 'disable', '--now', `${name}.service`]); // 未加载时失败无害
    try { fs.rmSync(unitPath); } catch {}
    run('systemctl', ['--user', 'daemon-reload']);
    return { kind: 'systemd', unitName: `${name}.service`, removed: true };
  }
  throw new Error(`不支持的平台: ${platform}（支持 Windows / macOS / Linux）`);
}

// ---------- stop 防复活钩子（`lanbook stop` 在扫端口杀进程之前调用） ----------
//
// 三平台语义一致：服务本次停下、不被服务管理器复活，下次登录自启恢复。
//   win32   写停止标记，autostart-task.cmd 守护循环检测到后退出（服务进程由 stop 主流程杀）
//   darwin  bootout 卸载本次会话的 agent（launchd 向服务发 SIGTERM；plist 保留，
//           下次登录 launchd 重新加载）
//   linux   systemctl --user stop（enable 状态保留，下次登录 default.target 再拉起）
// 返回 { stopped, via }：stopped=true 表示已请求服务管理器停服务（进程退出有延迟，
// stop 主流程的端口扫描兜底）；返回 null 表示无自启守护需要处理。

function stopAutostartGuard(opts = {}) {
  const run = opts.run || defaultRun;
  const platform = platformOf(opts);
  const name = autostartTaskName();

  if (platform === 'win32') {
    const dataDir = opts.dataDir || resolveDataDir();
    const { stopFlag } = windowsWrapperPaths(dataDir);
    try { fs.writeFileSync(stopFlag, String(Date.now()), 'utf8'); } catch {}
    return null;
  }
  if (platform === 'darwin') {
    const plistPath = launchdPlistPath(name, homeDirOf(opts));
    if (!fs.existsSync(plistPath)) return null;
    run('launchctl', ['bootout', `gui/${uidOf(opts)}/${name}`]); // 未加载时失败无害
    return { stopped: true, via: 'launchd' };
  }
  if (platform === 'linux') {
    const unitPath = systemdUnitPath(name, opts);
    if (!fs.existsSync(unitPath)) return null;
    run('systemctl', ['--user', 'stop', `${name}.service`]); // 未加载时失败无害
    return { stopped: true, via: 'systemd' };
  }
  return null;
}

module.exports = {
  autostartTaskName,
  serviceLogPath,
  launchdPlistPath,
  systemdUserDir,
  systemdUnitPath,
  generateLaunchdPlist,
  generateSystemdUnit,
  describeAutostart,
  registerAutostart,
  removeAutostart,
  stopAutostartGuard,
};
